apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app
  namespace: argo-demo
  labels:
    app.kubernetes.io/name: food-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: food-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: food-app
    spec:
      containers:
        - name: food-app
          image: aadityasirsam/foodapplication:v1
          ports:
            - name: tcp
              containerPort: 8000
