apiVersion: v1
kind: Service
metadata:
  name: food-app
  namespace: argo-demo
  labels:
    app.kubernetes.io/name: food-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: food-app
  ports:
    - name: http
      protocol: TCP
      port: 80         # Service port
      targetPort: 8000 # Container port
