apiVersion: v1
kind: Service
metadata:
  name: food-app
  namespace: argo-demo
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: food-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
